common:
    #lid_topic:  "/velodyne_points"
    #imu_topic:  "/sensors/imu"
    lid_topic:  "/livox/lidar"
    imu_topic:  "/imu0"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 6
    blind: 2

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     100.0
    #extrinsic_T: [ 0, 0, 0.28]
    #extrinsic_R: [ 1, 0, 0, 
                   #0, 1, 0, 
                   #0, 0, 1]
    # kitti外参
    #extrinsicTrans: [-8.086759e-01, 3.195559e-01, -7.997231e-01]
    #extrinsicRot: [9.999976e-01, 7.553071e-04, -2.035826e-03,
                  #-7.854027e-04, 9.998898e-01, -1.482298e-02,
                  #2.024406e-03, 1.482454e-02, 9.998881e-01]
    
    
    # hilti数据集参数
    #extrinsic_T: [ -0.001, -0.00855, 0.055 ]
    
    # hilti数据集参数
    #extrinsic_R: [ -0.0000000, -1.0000000,  0.0000000,
                    #-1.0000000, -0.0000000,  0.0000000,
                    #0.0000000,  0.0000000, -1.0000000 ]
    #darpa数据集参数
    #extrinsic_T: [ 0.00432374, 0.037466, 0.063319 ]
    #extrinsic_R: [  0.9996573, -0.0261770,  0.0000000,
                    #0.0261770,  0.9996573,  0.0000000,
                    #0.0000000,  0.0000000,  1.0000000 ]
    # WTU数据集
    extrinsic_T: [ -0.082, 0.061, 0.025 ]
    extrinsic_R: [  0.00190016,  -0.99992,   0.0124826,  
                    0.99998,     0.00182469, -0.00605486,   
                    0.0060316,   0.0124938,    0.999904 ]
          

publish:     
    scan_publish_en:  true       # 'false' will close all the point cloud output
    dense_publish_en: true       # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # output the point cloud scans in IMU-body-frame